"""Add User model and Firebase authentication

Revision ID: a9377098dad8
Revises: 5ab1d083c72c
Create Date: 2025-12-18 19:25:01.967770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9377098dad8'
down_revision: Union[str, None] = '5ab1d083c72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('lighthouse_performance', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('lighthouse_accessibility', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('lighthouse_seo', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('lighthouse_best_practices', sa.Float(), nullable=True))
    op.alter_column('reports', 'ai_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'ai_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('reports', 'lighthouse_best_practices')
    op.drop_column('reports', 'lighthouse_seo')
    op.drop_column('reports', 'lighthouse_accessibility')
    op.drop_column('reports', 'lighthouse_performance')
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
